ayurvedic={
    16: 'Brahmi',
    56: 'Turmeric',
    5: 'Amla (Indian Gooseberry)',
    48: 'Shatavari',
    30: 'Haritaki',
    13: 'Bhringraj',
    6: 'Arjuna',
    27: 'Guggul',
    37: 'Manjistha',
    46: 'Shankhpushpi',
    18: 'Chandan (Sandalwood)',
    35: 'Kutki',
    2: 'Amalaki',
    44: 'Punarnava',
    40: 'Mustard Oil',
    32: 'Hing (Asafoetida)',
    0: 'Ajwain (Carom Seeds)',
    34: 'Kapikachhu (Mucuna Pruriens)',
    20: 'Giloy',
    8: 'Ashwagandha',
    41: 'Neem',
    55: 'Tulsi (Holy Basil)',
    53: 'Triphala',
    47: 'Shankhpushpi (Convolvulus pluricaulis)',
    38: 'Manjistha (Rubia cordifolia)',
    19: 'Chyawanprash',
    54: 'Triphala Guggul',
    43: 'Pippali (Long Pepper)',
    60: 'Yashtimadhu (Licorice)',
    50: 'Shilajit',
    23: 'Gokshura (Tribulus Terrestris)',
    58: 'Vidarikanda (Pueraria Tuberosa)',
    11: 'Bael (Wood Apple)',
    39: 'Mulethi (Licorice)',
    25: 'Guduchi (Tinospora Cordifolia)',
    1: 'Aloe Vera',
    33: 'Kalmegh (Andrographis)',
    52: 'Trikatu',
    42: 'Neem (Azadirachta indica)',
    28: 'Guggul (Commiphora wightii)',
    36: 'Kutki (Picrorhiza kurroa)',
    22: 'Gokhru (Tribulus terrestris)',
    7: 'Arjuna (Terminalia arjuna)',
    31: 'Haritaki (Terminalia chebula)',
    45: 'Punarnava (Boerhavia diffusa)',
    9: 'Ashwagandha (Withania somnifera)',
    14: 'Bhringraj (Eclipta alba)',
    17: 'Brahmi (Bacopa monnieri)',
    29: 'Haridra (Turmeric)',
    21: 'Giloy (Tinospora cordifolia)',
    49: 'Shatavari (Asparagus racemosus)',
    26: 'Guduchi (Tinospora cordifolia)',
    12: 'Bhallataka (Semicarpus anacardium)',
    51: 'Shilajit (Mineral Pitch)',
    24: 'Gokshura (Tribulus terrestris)',
    59: 'Vidarikanda (Pueraria tuberosa)',
    10: 'Bael (Aegle marmelos)',
    57: 'Turmeric (Curcuma longa)',
    4: 'Amla (Emblica officinalis)',
    15: 'Black Seed Oil (Kalonji)',
    3: 'Amalaki (Indian Gooseberry)'
}

symptoms={
    'Memory Enhancement': 39,
    'Cognitive Function': 11,
    'Joint Pain': 34,
    'Inflammation': 32,
    'Digestive Aid': 16,
    'Hair Health': 24,
    'Digestive Health': 17,
    'Immunity': 30,
    'Hormonal Balance': 27,
    'Reproductive Health': 45,
    'Detoxification': 14,
    'Hair Loss': 25,
    'Scalp Health': 48,
    'Heart Health': 26,
    'Blood Pressure': 6,
    'Cholesterol Management': 10,
    'Weight Loss': 59,
    'Skin Detoxification': 50,
    'Blood Purification': 8,
    'Anxiety Relief': 3,
    'Skin Care': 49,
    'Aromatherapy': 4,
    'Liver Detoxification': 37,
    'Antioxidant': 2,
    'Kidney Health': 35,
    'Fluid Retention': 21,
    'Muscle Pain': 42,
    'Gas Relief': 22,
    'Indigestion': 31,
    'Bloating': 5,
    'Libido Enhancement': 36,
    'Mood Support': 41,
    'Immune Booster': 28,
    'Fever': 20,
    'Stress Relief': 57,
    'Energy': 19,
    'Skin Health': 52,
    'Immune Support': 29,
    'Respiratory Health': 46,
    'Colon Cleansing': 12,
    'Weight Management': 60,
    'Cough': 13,
    'Sore Throat': 53,
    'Gastric Ulcers': 23,
    'Stamina': 54,
    'Anti-Aging': 0,
    'Vitality': 58,
    'Strength': 55,
    'Diarrhea': 15,
    'Skin Healing': 51,
    'Scalp Care': 47,
    'Cholesterol Control': 9,
    'Liver Health': 38,
    'Metabolism Booster': 40,
    'Oral Care': 43,
    'Edema': 18,
    'Anti-Inflammatory': 1,
    'Joint Health': 33,
    'Pain Relief': 44,
    'Stress Reduction': 56,
    'Blood Pressure Control': 7
}

allopathicO={
    38: 'Nootropics, Memory Enhancers',
    35: 'NSAIDs, Digestive Medications',
    22: 'Hair Supplements, Immune Boosters',
    24: 'Hormone Replacement Therapy',
    30: 'Laxatives, Detox Supplements',
    34: 'Minoxidil, Scalp Treatments',
    7: 'Beta-Blockers, ACE Inhibitors',
    41: 'Statins, Weight Loss Medications',
    8: 'Blood Cleansers, Skin Detox',
    20: 'Ginkgo Biloba, SSRIs',
    39: 'Skin Creams, Aromatherapy Oils',
    33: 'Liver Supplements, Digestive Aids',
    14: 'Digestive Enzymes, Antioxidants',
    15: 'Diuretics, Kidney Supplements',
    42: 'Topical Analgesics, Muscle Rubs',
    19: 'Gas Relief Medications',
    1: 'Antacids, Digestive Aids',
    18: 'Erectile Dysfunction Medications',
    4: 'Antipyretics, Immune Boosters',
    5: 'Anxiolytics, Stimulants',
    2: 'Antibiotics, Skin Creams',
    11: 'Cough Syrups, Anxiolytics',
    29: 'Laxatives, Colon Cleansers',
    27: 'Immune Boosters, Energy Supplements',
    44: 'Weight Loss Supplements, Digestive Aids',
    12: 'Cough Syrups, Digestive Aids',
    10: 'Cough Syrups, Antacids',
    16: 'Energy Supplements, Anti-Aging Creams',
    31: 'Libido Enhancers, Kidney Supplements',
    17: 'Energy Supplements, Respiratory Herbs',
    3: 'Antidiarrheal Medications',
    25: 'Hormone Supplements, Fertility Herbs',
    43: 'Topical Ointments',
    21: 'Hair Oils',
    9: 'Cholesterol Medications',
    32: 'Liver Supplements',
    36: 'Nootropics',
    13: 'Digestive Aids',
    6: 'Ayurveda, Traditional Medicine',
    0: 'Adaptogens, Hormone Support',
    40: 'Skin Supplements, Immune Boosters',
    28: 'Immune Boosters, Respiratory Herbs',
    37: 'Nootropics, Adaptogens',
    26: 'Immune Boosters, Digestive Aids',
    23: 'Heart Supplements, Blood Pressure Medications'
}

allopathic={
    'Nootropics, Memory Enhancers': 38,
    'NSAIDs, Digestive Medications': 35,
    'Hair Supplements, Immune Boosters': 22,
    'Hormone Replacement Therapy': 24,
    'Laxatives, Detox Supplements': 30,
    'Minoxidil, Scalp Treatments': 34,
    'Beta-Blockers, ACE Inhibitors': 7,
    'Statins, Weight Loss Medications': 41,
    'Blood Cleansers, Skin Detox': 8,
    'Ginkgo Biloba, SSRIs': 20,
    'Skin Creams, Aromatherapy Oils': 39,
    'Liver Supplements, Digestive Aids': 33,
    'Digestive Enzymes, Antioxidants': 14,
    'Diuretics, Kidney Supplements': 15,
    'Topical Analgesics, Muscle Rubs': 42,
    'Gas Relief Medications': 19,
    'Antacids, Digestive Aids': 1,
    'Erectile Dysfunction Medications': 18,
    'Antipyretics, Immune Boosters': 4,
    'Anxiolytics, Stimulants': 5,
    'Antibiotics, Skin Creams': 2,
    'Cough Syrups, Anxiolytics': 11,
    'Laxatives, Colon Cleansers': 29,
    'Immune Boosters, Energy Supplements': 27,
    'Weight Loss Supplements, Digestive Aids': 44,
    'Cough Syrups, Digestive Aids': 12,
    'Cough Syrups, Antacids': 10,
    'Energy Supplements, Anti-Aging Creams': 16,
    'Libido Enhancers, Kidney Supplements': 31,
    'Energy Supplements, Respiratory Herbs': 17,
    'Antidiarrheal Medications': 3,
    'Hormone Supplements, Fertility Herbs': 25,
    'Topical Ointments': 43,
    'Hair Oils': 21,
    'Cholesterol Medications': 9,
    'Liver Supplements': 32,
    'Nootropics': 36,
    'Digestive Aids': 13,
    'Ayurveda, Traditional Medicine': 6,
    'Adaptogens, Hormone Support': 0,
    'Skin Supplements, Immune Boosters': 40,
    'Immune Boosters, Respiratory Herbs': 28,
    'Nootropics, Adaptogens': 37,
    'Immune Boosters, Digestive Aids': 26,
    'Heart Supplements, Blood Pressure Medications': 23
}

ingredients={
    18: 'Brahmi (Bacopa monnieri) leaves/extract',
    61: 'Turmeric (Curcuma longa) rhizome/extract',
    3: 'Amla (Emblica officinalis) fruit/extract',
    52: 'Shatavari (Asparagus racemosus) root/extract',
    31: 'Haritaki (Terminalia chebula) fruit/extract',
    14: 'Bhringraj (Eclipta prostrata) leaves/extract',
    6: 'Arjuna (Terminalia arjuna) bark/extract',
    29: 'Guggul (Commiphora wightii) resin/extract',
    38: 'Manjistha (Rubia cordifolia) root/extract',
    50: 'Shankhpushpi (Convolvulus pluricaulis) herb',
    20: 'Chandan (Santalum album) wood/extract',
    36: 'Kutki (Picrorhiza kurroa) root/extract',
    2: 'Amalaki (Emblica officinalis) fruit/extract',
    47: 'Punarnava (Boerhavia diffusa) root/extract',
    42: 'Mustard Oil (Brassica juncea)',
    33: 'Hing (Ferula assa-foetida)',
    0: 'Ajwain (Trachyspermum ammi) seeds',
    35: 'Kapikachhu (Mucuna pruriens) seeds/extract',
    21: 'Giloy (Tinospora cordifolia) stem/extract',
    8: 'Ashwagandha (Withania somnifera) root/extract',
    44: 'Neem (Azadirachta indica) leaves/extract',
    59: 'Tulsi (Ocimum sanctum) leaves/extract',
    57: 'Triphala (Amla, Haritaki, Bibhitaki) fruits',
    5: 'Amla, Ashwagandha, Ghee, Honey, Herbs',
    58: 'Triphala, Guggul',
    46: 'Pippali (Piper longum) fruit/extract',
    65: 'Yashtimadhu (Glycyrrhiza glabra) root/extract',
    54: 'Shilajit (Mineral Pitch)',
    24: 'Gokshura (Tribulus terrestris) fruit/extract',
    63: 'Vidarikanda (Pueraria tuberosa) root/extract',
    10: 'Bael (Aegle marmelos) fruit/extract',
    40: 'Mulethi (Glycyrrhiza glabra) root/extract',
    26: 'Guduchi (Tinospora cordifolia) stem/extract',
    1: 'Aloe Vera Gel',
    13: 'Bhringraj (Eclipta alba) leaves',
    28: 'Guggul (Commiphora wightii) resin',
    34: 'Kalmegh (Andrographis paniculata)',
    17: 'Brahmi (Bacopa monnieri) leaves',
    55: 'Trikatu (Long Pepper, Ginger, Black Pepper)',
    45: 'Neem Leaves, Neem Oil',
    30: 'Guggul Resin',
    51: 'Shankhpushpi Leaves, Extract',
    37: 'Kutki Root, Kutki Extract',
    23: 'Gokhru Fruit, Gokhru Extract',
    7: 'Arjuna Bark, Arjuna Extract',
    32: 'Haritaki Fruit, Haritaki Extract',
    48: 'Punarnava Root, Punarnava Extract',
    9: 'Ashwagandha Root, Ashwagandha Extract',
    56: 'Triphala (Amla, Haritaki, Bibhitaki)',
    15: 'Bhringraj Leaves, Bhringraj Oil',
    60: 'Tulsi Leaves, Tulsi Extract',
    19: 'Brahmi Leaves, Brahmi Extract',
    62: 'Turmeric Rhizome, Turmeric Extract',
    22: 'Giloy Stem, Giloy Extract',
    4: 'Amla Fruit, Amla Extract',
    53: 'Shatavari Root, Shatavari Extract',
    27: 'Guduchi Stem, Guduchi Extract',
    39: 'Manjistha Root, Manjistha Extract',
    12: 'Bhallataka Fruit, Bhallataka Extract',
    25: 'Gokshura Fruit, Gokshura Extract',
    64: 'Vidarikanda Root, Vidarikanda Extract',
    11: 'Bael Fruit, Bael Extract',
    41: 'Mulethi Root, Mulethi Extract',
    43: 'Neem (Azadirachta indica) leaves',
    16: 'Black Cumin Seed (Nigella sativa) oil',
    49: 'Shankhpushpi (Convolvulus pluricaulis)'
}

commonName={
    41: 'Memory',
    9: 'Cognitive Health',
    34: 'Inflammation',
    15: 'Digestion',
    25: 'Hair Health',
    32: 'Immunity',
    28: 'Hormonal Balance',
    20: 'Fertility',
    16: 'Digestive Health',
    12: 'Detox',
    26: 'Hair Loss',
    48: 'Scalp Health',
    27: 'Heart Health',
    30: 'Hypertension',
    8: 'Cholesterol Control',
    57: 'Weight Loss',
    6: 'Blood Purification',
    50: 'Skin Detox',
    2: 'Anxiety',
    49: 'Skin Care',
    3: 'Aromatherapy',
    40: 'Liver Health',
    1: 'Antioxidant',
    37: 'Kidney Health',
    17: 'Edema',
    36: 'Joint Pain',
    44: 'Muscle Pain',
    22: 'Gas Relief',
    33: 'Indigestion',
    4: 'Bloating',
    38: 'Libido',
    43: 'Mood Support',
    21: 'Fever',
    53: 'Stress',
    19: 'Energy',
    51: 'Skin Health',
    47: 'Respiratory Health',
    10: 'Colon Health',
    11: 'Cough',
    52: 'Sore Throat',
    23: 'Gastric Ulcers',
    0: 'Anti-Aging',
    56: 'Vitality',
    14: 'Diarrhea',
    46: 'Reproduction',
    24: 'Hair Growth',
    7: 'Cholesterol',
    39: 'Liver Detoxification',
    42: 'Metabolism',
    31: 'Immune Support',
    55: 'Stress Relief',
    5: 'Blood Pressure',
    13: 'Detoxification',
    18: 'Edema Relief',
    35: 'Joint Health',
    45: 'Pain Relief',
    29: 'Hormones',
    54: 'Stress Reduction'
}

file = {'Inflammation': ['Turmeric, Boswellia, Ginger', 'Turmeric: 500mg, twice daily. Boswellia: 500mg, twice daily. Ginger: 500mg, twice daily.', 'Adopt a healthy diet rich in fruits, vegetables, and whole grains. Avoid processed foods, sugary drinks, and excessive amounts of saturated and unhealthy fats. Engage in regular exercise, such as brisk walking, swimming, or cycling, for at least 30 minutes most days of the week. Manage stress through techniques like yoga, meditation, or deep breathing.'],
       'Joint Pain': ['Ashwagandha, Boswellia, Curcumin, Ginger', '500mg of each herb, twice daily', 'Regular exercise, warm baths, massage with sesame oil.'],
       'Hair Loss': ['Bhringraj, Amla, Brahmi, Shikakai', 'Bhringraj: 1-2 teaspoons of powder mixed with coconut oil, applied to the scalp and left overnight. Amla: 1-2 teaspoons of powder mixed with coconut oil, applied to the scalp and left overnight. Brahmi: 1-2 teaspoons of powder mixed with coconut oil, applied to the scalp and left overnight. Shikakai: 1-2 tablespoons of powder mixed with water, used as a shampoo.', 'Massage your scalp regularly with coconut oil or almond oil. Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Get regular exercise. Avoid stress. Get enough sleep.'],
       'Muscle Pain': ['Ashwagandha, Boswellia, Curcumin, Ginger', '500mg of each herb, twice daily', 'Regular exercise, warm baths, massage with sesame oil.'], 
       'Indigestion': ['Triphala, Haritaki, Amla, Bibhitaki', 'Triphala: 1-2 teaspoons of powder mixed with warm water, taken before bedtime. Haritaki: 1-2 teaspoons of powder mixed with warm water, taken before bedtime. Amla: 1-2 teaspoons of powder mixed with warm water, taken before bedtime. Bibhitaki: 1-2 teaspoons of powder mixed with warm water, taken before bedtime.', 'Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Avoid processed foods, sugary drinks, and excessive amounts of caffeine and alcohol. Drink plenty of water. Get regular exercise. Manage stress.'], 
       'Bloating': ['Triphala, Haritaki, Amla, Bibhitaki', 'Triphala: 1-2 teaspoons of powder mixed with warm water, taken before bedtime. Haritaki: 1-2 teaspoons of powder mixed with warm water, taken before bedtime. Amla: 1-2 teaspoons of powder mixed with warm water, taken before bedtime. Bibhitaki: 1-2 teaspoons of powder mixed with warm water, taken before bedtime.', 'Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Avoid processed foods, sugary drinks, and excessive amounts of caffeine and alcohol. Drink plenty of water. Get regular exercise. Manage stress.'], 
       'Fever': ['Guduchi, Tulsi, Neem, Amla', 'Guduchi: 1-2 teaspoons of powder mixed with warm water, taken twice daily. Tulsi: 1-2 teaspoons of leaves boiled in water, taken twice daily. Neem: 1-2 teaspoons of leaves boiled in water, taken twice daily. Amla: 1-2 teaspoons of powder mixed with warm water, taken twice daily.', 'Drink plenty of fluids, especially water. Rest and avoid strenuous activity. Apply a cold compress to your forehead, chest, and back. Take over-the-counter pain relievers, such as ibuprofen or acetaminophen. If your fever is over 103 degrees Fahrenheit, seek medical attention.'], 
       'Cough': ['Honey, Garlic, Hot Liquid', 'Honey: 1-2 teaspoons in a cup of hot water, several times a day. Garlic: Crush a garlic clove and mix it with honey. Take 1-2 teaspoons of the mixture several times a day. Hot Liquid: Drink hot liquids, such as tea, soup, or hot water, throughout the day.', 'Get plenty of rest. Wash your hands frequently. Avoid touching your face. Cover your mouth and nose when coughing or sneezing. Use a humidifier or saline nasal spray to keep your nasal passages moist. Gargle with salt water several times a day.'], 
       'Sore Throat': ['Honey, Garlic, Hot Liquid', 'Honey: 1-2 teaspoons in a cup of hot water, several times a day. Garlic: Crush a garlic clove and mix it with honey. Take 1-2 teaspoons of the mixture several times a day. Hot Liquid: Drink hot liquids, such as tea, soup, or hot water, throughout the day.', 'Gargle with salt water several times a day. Take over-the-counter pain relievers, such as ibuprofen or acetaminophen. Get plenty of rest. Avoid smoking and secondhand smoke. Use a humidifier or saline nasal spray to keep your nasal passages moist.'], 
       'Diarrhea': ['Bananas, Rice, Applesauce, Toast', 'Bananas: Eat 1-2 bananas per day. Rice: Eat cooked rice without any added fat or spices. Applesauce: Eat unsweetened applesauce without any added sugar. Toast: Eat dry toast without any butter or jam.', 'Drink plenty of fluids, especially water and electrolyte-rich drinks. Avoid caffeine and alcohol. Get plenty of rest. Wash your hands frequently. Avoid eating raw or undercooked foods. Cook meats and fish thoroughly. Keep your kitchen clean.'], 
       'High Blood Pressure': ['Garlic, Amla, Arjuna, Sarpagandha', 'Garlic: 1-2 cloves of garlic, crushed and mixed with honey, taken twice daily. Amla: 1-2 teaspoons of amla powder mixed with honey, taken twice daily. Arjuna: 1-2 teaspoons of arjuna powder mixed with honey, taken twice daily. Sarpagandha: 1-2 teaspoons of sarpagandha powder mixed with honey, taken twice daily.', 'Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Avoid processed foods, sugary drinks, and excessive amounts of caffeine and alcohol. Get regular exercise. Manage stress. Maintain a healthy weight.'], 
       'Low Blood Pressure': ['Licorice, Ashwagandha, Ginseng, Cardamom', 'Licorice: 1-2 teaspoons of licorice root powder mixed with honey, taken twice daily. Ashwagandha: 1-2 teaspoons of ashwagandha powder mixed with honey, taken twice daily. Ginseng: 1-2 teaspoons of ginseng powder mixed with honey, taken twice daily. Cardamom: 1-2 teaspoons of cardamom powder mixed with honey, taken twice daily.', 'Drink plenty of fluids, especially water and electrolyte-rich drinks. Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Avoid processed foods, sugary drinks, and excessive amounts of caffeine and alcohol. Get regular exercise. Manage stress. Avoid sudden changes in position.'], 
       'Headache': ['Ginger, Peppermint, Feverfew, Willow Bark', 'Ginger: Grate a small piece of ginger and mix it with honey. Take 1-2 teaspoons of the mixture several times a day. Peppermint: Steep 1-2 teaspoons of dried peppermint leaves in hot water for 10 minutes. Strain and drink the tea several times a day. Feverfew: Take 1-2 capsules of feverfew extract daily. Willow Bark: Take 1-2 capsules of willow bark extract daily.', 'Get plenty of rest. Avoid caffeine and alcohol. Apply a cold compress to your forehead or temples. Take over-the-counter pain relievers, such as ibuprofen or acetaminophen. Identify and avoid triggers that may cause headaches.'], 
       'Migraine': ['Ginger, Peppermint, Feverfew, Butterbur', 'Ginger: Grate a small piece of ginger and mix it with honey. Take 1-2 teaspoons of the mixture several times a day. Peppermint: Steep 1-2 teaspoons of dried peppermint leaves in hot water for 10 minutes. Strain and drink the tea several times a day. Feverfew: Take 1-2 capsules of feverfew extract daily. Butterbur: Take 1-2 capsules of butterbur extract daily.', 'Get plenty of rest. Avoid caffeine and alcohol. Apply a cold compress to your forehead or temples. Take over-the-counter pain relievers, such as ibuprofen or acetaminophen. Identify and avoid triggers that may cause migraines.'],
       'Asthma': ['Honey, Garlic, Turmeric, Ginger', 'Honey: 1-2 teaspoons of honey mixed with warm water, taken twice daily. Garlic: Crush a garlic clove and mix it with honey. Take 1-2 teaspoons of the mixture several times a day. Turmeric: 1-2 teaspoons of turmeric powder mixed with warm milk, taken twice daily. Ginger: Grate a small piece of ginger and mix it with honey. Take 1-2 teaspoons of the mixture several times a day.', 'Avoid triggers that may cause asthma attacks, such as dust, pollen, smoke, and strong odors. Get regular exercise. Manage stress. Use a humidifier or saline nasal spray to keep your nasal passages moist. Take prescribed medications as directed by your doctor.'],
       'Allergies': ['Honey, Garlic, Quercetin, Probiotics', 'Honey: 1-2 teaspoons of honey mixed with warm water, taken twice daily. Garlic: Crush a garlic clove and mix it with honey. Take 1-2 teaspoons of the mixture several times a day. Quercetin: Take 500-1,000 mg of quercetin supplements daily. Probiotics: Take a probiotic supplement that contains at least 10 billion CFUs daily.', 'Avoid exposure to allergens, such as pollen, dust, and pet dander. Use a HEPA filter in your home. Wash your hands frequently. Take over-the-counter antihistamines or decongestants to relieve symptoms. Get allergy shots if necessary.'], 
       'Depression': ['Ashwagandha, Brahmi, Saffron, Turmeric', 'Ashwagandha: Take 500-1,000 mg of ashwagandha extract daily. Brahmi: Take 500-1,000 mg of brahmi extract daily. Saffron: Take 15-30 mg of saffron extract daily. Turmeric: Take 500-1,000 mg of turmeric extract daily.', 'Get regular exercise. Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Avoid processed foods, sugary drinks, and excessive amounts of caffeine and alcohol. Get enough sleep. Practice relaxation techniques, such as meditation or yoga. Spend time in nature. Talk to a therapist or counselor.'], 
       'Anxiety': ['Ashwagandha, Brahmi, Lavender, Chamomile', 'Ashwagandha: Take 500-1,000 mg of ashwagandha extract daily. Brahmi: Take 500-1,000 mg of brahmi extract daily. Lavender: Inhale lavender essential oil or take lavender supplements. Chamomile: Drink chamomile tea or take chamomile supplements.', 'Get regular exercise. Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Avoid processed foods, sugary drinks, and excessive amounts of caffeine and alcohol. Get enough sleep. Practice relaxation techniques, such as meditation or yoga. Spend time in nature. Talk to a therapist or counselor.'],
       'Eczema': ['Neem Oil, Coconut Oil, Turmeric', 'Neem Oil: Apply a thin layer of neem oil to the affected area, twice daily. Coconut Oil: Apply a thin layer of coconut oil to the affected area, several times a day. Turmeric: Mix turmeric powder with coconut oil to make a paste. Apply the paste to the affected area, twice daily.', 'Avoid harsh soaps and detergents. Wear loose, comfortable clothing made from natural fibers, such as cotton. Take lukewarm baths or showers. Moisturize your skin regularly. Use a humidifier to keep the air in your home moist. Avoid scratching the affected area.'], 'Psoriasis': ['Neem Oil, Coconut Oil, Aloe Vera Gel', 'Neem Oil: Apply a thin layer of neem oil to the affected area, twice daily. Coconut Oil: Apply a thin layer of coconut oil to the affected area, several times a day. Aloe Vera Gel: Apply a thin layer of aloe vera gel to the affected area, several times a day.', 'Avoid harsh soaps and detergents. Wear loose, comfortable clothing made from natural fibers, such as cotton. Take lukewarm baths or showers. Moisturize your skin regularly. Use a humidifier to keep the air in your home moist. Avoid scratching the affected area. Eat a healthy diet that is rich in fruits, vegetables, and whole grains.'], 'Acne': ['Neem Face Wash, Multani Mitti Face Mask, Tea Tree Oil', 'Neem Face Wash: Use a neem face wash to cleanse your face twice daily. Multani Mitti Face Mask: Mix multani mitti powder with water to make a paste. Apply the paste to your face and leave it on for 15-20 minutes. Rinse it off with water. Tea Tree Oil: Apply a small amount of tea tree oil to the affected area, twice daily.', 'Wash your face twice daily with a gentle cleanser. Avoid harsh soaps and scrubs. Moisturize your skin regularly. Avoid touching your face. Change your pillowcase frequently. Eat a healthy diet that is rich in fruits, vegetables, and whole grains.'], 
    'Cold': ['Honey, Garlic, Hot Liquid', 'Honey: 1-2 teaspoons in a cup of hot water, several times a day. Garlic: Crush a garlic clove and mix it with coconut oil. Apply the mixture to the soles of your feet before bedtime. Hot Liquid: Drink hot liquids, such as tea, soup, or hot water, throughout the day.', 'Get plenty of rest. Wash your hands frequently. Avoid touching your face. Cover your mouth and nose when coughing or sneezing. Use a humidifier or saline nasal spray to keep your nasal passages moist. Gargle with salt water several times a day.'], 
        'Flu': ['Elderberries, Echinacea, Vitamin C', 'Elderberries: Take 1-2 teaspoons of elderberry syrup or tincture, three times daily. Echinacea: Take 500-1,000 mg of echinacea extract, three times daily. Vitamin C: Take 1,000-2,000 mg of vitamin C, three times daily.', 'Get plenty of rest. Drink plenty of fluids, especially water and herbal teas. Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Avoid alcohol and caffeine. Use a humidifier or saline nasal spray to keep your nasal passages moist. Gargle with salt water several times a day.'], 
        'Pneumonia': ['Honey, Garlic, Hot Liquid', 'Honey: 1-2 teaspoons in a cup of hot water, several times a day. Garlic: Crush a garlic clove and mix it with coconut oil. Apply the mixture to the soles of your feet before bedtime. Hot Liquid: Drink hot liquids, such as tea, soup, or hot water, throughout the day.', 'Get plenty of rest. Wash your hands frequently. Avoid touching your face. Cover your mouth and nose when coughing or sneezing. Use a humidifier or saline nasal spray to keep your nasal passages moist. Gargle with salt water several times a day.'], 
        'Ear Infection': ['Garlic Oil, Mullein Oil, Tea Tree Oil', 'Garlic Oil: 2-3 drops in the affected ear, twice daily. Mullein Oil: 2-3 drops in the affected ear, twice daily. Tea Tree Oil: 2-3 drops in the affected ear, twice daily.', 'Keep the ear clean and dry. Avoid swimming or getting water in the ear. Use a warm compress to relieve pain. Take over-the-counter pain relievers, such as ibuprofen or acetaminophen. Get plenty of rest.'], 
 'Urinary Tract Infection': ['Cranberry Juice, D-Mannose, Garlic', 'Cranberry Juice: Drink 1-2 glasses of cranberry juice daily. D-Mannose: Take 1-2 grams of D-mannose powder, three times daily. Garlic: Crush a garlic clove and mix it with coconut oil. Apply the mixture to the soles of your feet before bedtime.', 'Drink plenty of fluids, especially water. Avoid caffeine and alcohol. Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Get regular exercise. Practice good hygiene, including washing your hands frequently and urinating after sex. Avoid using harsh soaps or feminine hygiene products. Wear cotton underwear and loose clothing. Take sitz baths in warm water several times a day.'], 
 'Kidney Infection': ['Cranberry Juice, D-Mannose, Garlic', 'Cranberry Juice: Drink 1-2 glasses of cranberry juice daily. D-Mannose: Take 1-2 grams of D-mannose powder, three times daily. Garlic: Crush a garlic clove and mix it with coconut oil. Apply the mixture to the soles of your feet before bedtime.', 'Drink plenty of fluids, especially water. Avoid caffeine and alcohol. Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Get regular exercise. Practice good hygiene, including washing your hands frequently and urinating after sex. Avoid using harsh soaps or feminine hygiene products. Wear cotton underwear and loose clothing. Take sitz baths in warm water several times a day.'], 
 'Bladder Infection': ['Cranberry Juice, D-Mannose, Garlic', 'Cranberry Juice: Drink 1-2 glasses of cranberry juice daily. D-Mannose: Take 1-2 grams of D-mannose powder, three times daily. Garlic: Crush a garlic clove and mix it with coconut oil. Apply the mixture to the soles of your feet before bedtime.', 'Drink plenty of fluids, especially water. Avoid caffeine and alcohol. Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Get regular exercise. Practice good hygiene, including washing your hands frequently and urinating after sex. Avoid using harsh soaps or feminine hygiene products. Wear cotton underwear and loose clothing. Take sitz baths in warm water several times a day.'], 
 'Chlamydia': ['Garlic, Oregano Oil, Tea Tree Oil', 'Garlic: Crush a garlic clove and mix it with coconut oil. Apply the mixture to the affected area, twice daily. Oregano Oil: Mix oregano oil with coconut oil. Apply the mixture to the affected area, twice daily. Tea Tree Oil: Mix tea tree oil with coconut oil. Apply the mixture to the affected area, twice daily.', 'Keep the affected area clean and dry. Avoid sexual contact until you and your partner have been treated. Get plenty of rest. Drink plenty of fluids. Eat a healthy diet that is rich in fruits, vegetables, and whole grains.'], 
 'Syphilis': ['Garlic, Oregano Oil, Tea Tree Oil', 'Garlic: Crush a garlic clove and mix it with coconut oil. Apply the mixture to the affected area, twice daily. Oregano Oil: Mix oregano oil with coconut oil. Apply the mixture to the affected area, twice daily. Tea Tree Oil: Mix tea tree oil with coconut oil. Apply the mixture to the affected area, twice daily.', 'Keep the affected area clean and dry. Avoid sexual contact until you and your partner have been treated. Get plenty of rest. Drink plenty of fluids. Eat a healthy diet that is rich in fruits, vegetables, and whole grains.'], 
 'Heart Disease': ['Garlic, Arjuna, Guggul', 'Garlic: Crush a garlic clove and mix it with honey. Consume the mixture on an empty stomach, once daily. Arjuna: Take 500-1,000 mg of arjuna extract, twice daily. Guggul: Take 500-1,000 mg of guggul extract, twice daily.', 'Eat a healthy diet that is low in saturated fat, cholesterol, and sodium. Get regular exercise. Maintain a healthy weight. Manage stress. Quit smoking. Limit alcohol consumption. Get regular checkups.'], 
 'Diabetes': ['Neem, Fenugreek, Bitter Melon', 'Neem: Take 1-2 teaspoons of neem powder with water, twice daily. Fenugreek: Soak 1-2 tablespoons of fenugreek seeds in water overnight. Drink the water on an empty stomach, in the morning. Bitter Melon: Drink bitter melon juice, once daily.', 'Eat a healthy diet that is low in sugar and processed foods. Get regular exercise. Maintain a healthy weight. Manage stress. Quit smoking. Limit alcohol consumption. Get regular checkups.'], 
 'Obesity': ['Green Tea, Garcinia Cambogia, Guggul', 'Green Tea: Drink 2-3 cups of green tea daily. Garcinia Cambogia: Take 500-1,000 mg of garcinia cambogia extract, three times daily. Guggul: Take 500-1,000 mg of guggul extract, twice daily.', 'Eat a healthy diet that is low in calories, fat, and sugar. Get regular exercise. Maintain a healthy weight. Manage stress. Quit smoking. Limit alcohol consumption. Get regular checkups.'], 
 'Arthritis': ['Turmeric, Boswellia, Ginger', 'Turmeric: Take 500-1,000 mg of turmeric extract, three times daily. Boswellia: Take 500-1,000 mg of boswellia extract, three times daily. Ginger: Take 500-1,000 mg of ginger extract, three times daily.', 'Eat a healthy diet that is rich in fruits, vegetables, and whole grains. Get regular exercise. Maintain a healthy weight. Manage stress. Quit smoking. Limit alcohol consumption. Get regular checkups.']}

home_Remedies={
    58: 'Yoga, Meditation, Brain-Boosting Foods',
    31: 'Hot Compress, Ginger Tea, Epsom Salt Bath',
    1: 'Aloe Vera Gel for Skin, Honey and Lemon for Digestion',
    60: 'Yoga, Meditation, Hormone-Balancing Diet',
    19: 'Fasting, Warm Water with Lemon, Fiber-Rich Foods',
    44: 'Scalp Massage, Aloe Vera Gel, Onion Juice',
    29: 'Heart-Healthy Diet, Exercise, Meditation',
    18: 'Exercise, Diet Modifications, Apple Cider Vinegar',
    16: 'Detox Diet, Hydration, Skin Brushing',
    37: 'Mindfulness, Deep Breathing, Herbal Teas',
    43: 'Sandalwood Paste, Lavender Oil, Steam Inhalation',
    17: 'Detox Diet, Milk Thistle, Castor Oil Packs',
    22: 'Ginger Tea, Fennel Seeds, Peppermint Oil',
    32: 'Hydration, Low-Sodium Diet, Dandelion Tea',
    49: 'Topical Application, Massage',
    7: 'Asafoetida in Warm Water, Ginger Tea, Fennel Seeds',
    0: 'Ajwain Water, Carom Seed Tea, Fennel-Ajwain Mix',
    30: 'Herbal Tea, Kapikachhu Capsules, Mucuna Extract',
    20: 'Giloy Juice, Decoction, Tablets',
    59: 'Yoga, Meditation, Deep Breathing',
    40: 'Neem Paste, Neem Oil, Neem Tea',
    54: 'Tulsi Tea, Chewing Leaves, Tulsi Inhalation',
    52: 'Triphala Powder, Triphala Capsules',
    15: 'Consumed as a Jam, Chyawanprash Tea',
    51: 'Triphala Guggul Tablets, Triphala Guggul Powder',
    41: 'Pippali Churna, Pippali Oil, Pippali Tea',
    35: 'Licorice Tea, Licorice Lozenges, Licorice Infusion',
    48: 'Shilajit Resin, Shilajit Capsules, Shilajit Tea',
    24: 'Gokshura Extract, Gokshura Capsules, Gokshura Tea',
    57: 'Vidarikanda Tea, Vidarikanda Powder, Vidarikanda Capsules',
    10: 'Bael Fruit Pulp, Bael Juice, Bael Tea',
    47: 'Shatavari Powder, Shatavari Capsules, Shatavari Tea',
    25: 'Guduchi Juice, Guduchi Tablets, Guduchi Infusion',
    2: 'Aloe Vera Gel, Aloe Vera Juice, Aloe Vera Capsules',
    12: 'Bhringraj Oil, Bhringraj Powder, Bhringraj Hair Mask',
    27: 'Guggul Capsules, Guggul Resin, Guggul Powder',
    33: 'Kalmegh Capsules, Kalmegh Extract, Kalmegh Tea',
    50: 'Trikatu Powder, Trikatu Capsules, Trikatu Tea',
    39: 'Neem Oil, Neem Capsules, Neem Powder',
    26: 'Guggul Capsules, Guggul Powder, Guggul Tablets',
    45: 'Shankhpushpi Powder, Shankhpushpi Capsules',
    34: 'Kutki Powder, Kutki Capsules, Kutki Tincture',
    23: 'Gokhru Extract, Gokhru Capsules, Gokhru Tea',
    6: 'Arjuna Capsules, Arjuna Powder, Arjuna Tea',
    28: 'Haritaki Powder, Haritaki Capsules, Haritaki Tea',
    42: 'Punarnava Capsules, Punarnava Powder, Punarnava Tea',
    8: 'Ashwagandha Capsules, Ashwagandha Powder, Ashwagandha Tea',
    53: 'Triphala Powder, Triphala Capsules, Triphala Tea',
    55: 'Tulsi Tea, Tulsi Capsules, Tulsi Tincture',
    14: 'Brahmi Powder, Brahmi Capsules, Brahmi Tea',
    56: 'Turmeric Powder, Turmeric Capsules, Turmeric Tea',
    21: 'Giloy Juice, Giloy Tablets, Giloy Powder',
    4: 'Amla Capsules, Amla Powder, Amla Chutney',
    36: 'Manjistha Powder, Manjistha Capsules, Manjistha Tea',
    11: 'Bhallataka Oil, Bhallataka Powder, Bhallataka Capsules',
    9: 'Ashwagandha Powder, Ashwagandha Capsules, Ashwagandha Tea',
    38: 'Neem Oil, Neem Capsules, Neem Leaf Extract',
    13: 'Black Seed Oil, Black Seed Capsules, Black Seed Tea',
    46: 'Shankhpushpi Powder, Shankhpushpi Capsules, Shankhpushpi Tea',
    3: 'Amalaki Powder, Amalaki Capsules, Amalaki Infusion',
    5: 'Arjuna Bark Powder, Arjuna Capsules, Arjuna Tea'
}

dosage={
    5: '300-500 mg daily',
    10: '500-2000 mg daily',
    8: '500-1000 mg daily',
    9: '500-1000 mg twice daily',
    13: 'External Application',
    4: '250-500 mg daily',
    12: 'Asafoetida Powder: 200-500 mg, Asafoetida Resin: 1-3 g',
    1: '1-2 tsp of seeds after meals',
    6: '300-600 mg daily',
    0: '1-2 tsp daily',
    3: '200-600 mg daily',
    2: '2-4 tbsp daily (juice)',
    11: 'Apply oil or mask regularly',
    14: 'Use with caution, consult an Ayurvedic practitioner',
    7: '500-1000'
}

diet_chart={
    5: 'Balanced diet with fish, leafy greens, and nuts',
    47: 'Turmeric milk, curries, and anti-inflammatory foods',
    31: 'Incorporate amla in salads, smoothies, and snacks',
    29: 'Include shatavari in soups, teas, and asparagus dishes',
    35: 'Increase fiber intake with fruits and vegetables',
    27: 'Include protein-rich foods and leafy greens',
    43: 'Reduce sodium and processed foods in the diet',
    36: 'Low-fat, high-fiber diet with fruits and vegetables',
    44: 'Stay hydrated and consume antioxidant-rich foods',
    24: 'Include brain-boosting foods like blueberries',
    60: 'Use sandalwood in face masks and aromatherapy',
    11: 'Consume a liver-friendly diet with cruciferous veggies',
    0: 'Add amalaki to smoothies and antioxidant-rich foods',
    37: 'Maintain proper hydration and reduce sodium intake',
    55: 'Use mustard oil for massage and pain relief',
    32: 'Incorporate asafoetida in cooking and digestive teas',
    48: 'Use ajwain in cooking and digestive infusions',
    26: 'Include kapikachhu in herbal teas and dietary supplements',
    41: 'Prepare giloy juice and consume it as per recommendations',
    22: 'Include ashwagandha in smoothies and herbal tea',
    56: 'Use neem in skincare routines and herbal teas',
    7: 'Brew tulsi tea and use it as a stress-relief remedy',
    19: 'Consume triphala as a digestive tonic and detoxifier',
    15: 'Consume chyawanprash directly or as a spread',
    9: 'Combine with a balanced diet and regular exercise',
    59: 'Use pippali as a spice and in herbal preparations',
    52: 'Use licorice in teas, infusions, and lozenges',
    18: 'Consume shilajit with warm milk or water',
    17: 'Consume gokshura in herbal teas and supplements',
    61: 'Use vidarikanda in herbal teas and dietary supplements',
    23: 'Include bael fruit pulp in diet and make bael tea',
    54: 'Use mulethi in teas, infusions, and lozenges',
    28: 'Include shatavari in herbal teas and supplements',
    42: 'Prepare guduchi juice or consume it in tablet form',
    3: 'Apply aloe vera gel topically for skin healing',
    51: 'Use bhringraj oil for scalp massage and hair masks',
    10: 'Combine with exercise and a balanced diet',
    38: 'Make kalmegh tea or take it in supplement form',
    2: 'Add trikatu to meals or take it as a supplement',
    57: 'Use neem oil for skin and oral care, or take capsules',
    12: 'Consume as a powder or in capsule form',
    33: 'Incorporate in herbal formulations and supplements',
    6: 'Brew gokhru tea or take capsules for kidney health',
    50: 'Use as a supplement or in herbal teas',
    25: 'Include in herbal formulations and as a tea',
    39: 'Make tea or take capsules for kidney support',
    13: 'Consume as a supplement, in tea, or with warm milk',
    49: 'Use as a daily supplement or in herbal teas',
    8: 'Brew tulsi tea or take capsules for immunity',
    20: 'Enhance memory with supplements or herbal teas',
    34: 'Incorporate turmeric into cooking or take supplements',
    16: 'Consume giloy juice or tablets for immunity',
    21: 'Include amla in salads, chutneys, or as a supplement',
    53: 'Use manjistha in herbal formulations and teas',
    4: 'Apply oil topically for joint pain or take capsules',
    1: 'Add to smoothies or take in supplement form',
    58: 'Use neem oil topically and neem leaf extract in supplements',
    45: 'Take black seed oil as a supplement or use it in cooking',
    14: 'Consume as a tea, in capsule form, or as a powder',
    30: 'Incorporate amalaki in smoothies, supplements, or infusions',
    46: 'Take in supplement form or make arjuna tea',
    40: 'Not Found'
}

yoga={
    10: 'Bhramari Pranayama, Sarvangasana (Shoulder Stand)',
    37: 'Surya Namaskar (Sun Salutation), Trikonasana (Triangle Pose)',
    18: 'Kapalbhati Pranayama, Halasana (Plow Pose)',
    15: 'Bhujangasana (Cobra Pose), Viparita Karani (Legs-Up-the-Wall Pose)',
    25: 'Paschimottanasana (Seated Forward Bend), Agnisar Kriya',
    7: 'Bhastrika Pranayama, Matsyasana (Fish Pose)',
    0: 'Anulom Vilom Pranayama, Setu Bandhasana (Bridge Pose)',
    42: 'Triyak Tadasana, Dhanurasana (Bow Pose)',
    13: 'Bhujangasana (Cobra Pose), Matsyendrasana (Half Spinal Twist)',
    22: 'Nadi Shodhana Pranayama (Alternate Nostril Breathing), Bhramari Pranayama (Humming Bee Breath)',
    32: 'Savasana (Corpse Pose), Ustrasana (Camel Pose)',
    17: 'Kapalbhati Pranayama, Bhujangasana (Cobra Pose)',
    27: 'Pavanamuktasana (Wind-Relieving Pose), Utkatasana (Chair Pose)',
    50: 'Vrikshasana (Tree Pose), Shavasana (Corpse Pose)',
    19: 'Marjariasana (Cat-Cow Pose), Gomukhasana (Cow Face Pose)',
    46: 'Vajrasana (Diamond Pose), Agnisar Kriya',
    6: 'Bhastrika Pranayama (Bellows Breath), Vajrasana (Diamond Pose)',
    16: 'Dhanurasana (Bow Pose), Urdhva Dhanurasana (Wheel Pose)',
    38: 'Tadasana (Mountain Pose), Anulom Vilom Pranayama (Alternate Nostril Breathing)',
    31: 'Savasana (Corpse Pose), Bhramari Pranayama (Humming Bee Breath)',
    12: 'Bhujangasana (Cobra Pose), Matsyasana (Fish Pose)',
    1: 'Ardha Matsyendrasana (Half Spinal Twist), Anulom Vilom Pranayama (Alternate Nostril Breathing)',
    26: 'Paschimottanasana (Seated Forward Bend), Ardha Halasana (Half Plough Pose)',
    48: 'Vajrasana (Diamond Pose), Bhramari Pranayama (Humming Bee Breath)',
    41: 'Trikonasana (Triangle Pose), Navasana (Boat Pose)',
    43: 'Ujjayi Pranayama (Victorious Breath), Ardha Matsyendrasana (Half Spinal Twist)',
    36: 'Surya Namaskar (Sun Salutation), Bhastrika Pranayama (Bellows Breath)',
    14: 'Bhujangasana (Cobra Pose), Ustrasana (Camel Pose)',
    2: 'Ardha Matsyendrasana (Half Spinal Twist), Pawanmuktasana (Wind-Relieving Pose)',
    35: 'Supta Baddha Konasana (Reclining Bound Angle Pose), Anulom Vilom Pranayama (Alternate Nostril Breathing)',
    49: 'Vrikshasana (Tree Pose), Bhastrika Pranayama (Bellows Breath)',
    20: 'Matsyasana (Fish Pose), Anulom Vilom Pranayama (Alternate Nostril Breathing)',
    30: 'Sasangasana (Rabbit Pose), Bhastrika Pranayama (Bellows Breath)',
    11: 'Bhujangasana (Cobra Pose), Anulom Vilom Pranayama (Alternate Nostril Breathing)',
    44: 'Ujjayi Pranayama (Victorious Breath), Pavanmuktasana (Wind-Relieving Pose)',
    40: 'Trikonasana (Triangle',
    24: 'Padmasana (Lotus Pose), Bhastrika Pranayama (Bellows Breath)',
    8: "Bhramari Pranayama (Humming Bee Breath), Balasana (Child's Pose)",
    47: 'Vajrasana (Diamond Pose), Anulom Vilom Pranayama (Alternate Nostril Breathing)',
    34: 'Sukhasana (Easy Pose), Nadi Shodhana Pranayama (Alternate Nostril Breathing)',
    29: 'Pavanmuktasana (Wind-Relieving Pose), Sheetkari Pranayama (Hissing Breath)',
    5: 'Bhastrika Pranayama (Bellows Breath), Setu Bandhasana (Bridge Pose)',
    4: "Balasana (Child's Pose), Brahmari Pranayama (Bee Breath)",
    28: 'Pavanmuktasana (Wind-Relieving Pose), Anulom Vilom Pranayama (Alternate Nostril Breathing)',
    33: 'Sukhasana (Easy Pose), Bhramari Pranayama (Humming Bee Breath)',
    21: 'Matsyasana (Fish Pose), Bhastrika Pranayama (Bellows Breath)',
    23: 'Not Found',
    3: "Balasana (Child's Pose), Anulom Vilom Pranayama (Alternate Nostril Breathing)",
    39: 'Tadasana (Mountain Pose), Bhastrika Pranayama (Bellows Breath)',
    45: 'Ustrasana (Camel Pose), Bhramari Pranayama (Humming Bee Breath)',
    9: 'Bhramari Pranayama (Humming Bee Breath), Vajrasana (Diamond Pose)'
}