var symp = [
  "Joint Pain",
  "Inflammation",
  "Hair Loss",
  "Muscle Pain",
  "Indigestion",
  "Bloating",
  "Fever",
  "Cough",
  "Sore Throat",
  "Diarrhea",
  "High Blood Pressure",
  "Low Blood Pressure",
  "Headache",
  "Migraine",
  "Asthma",
  "Allergies",
  "Depression",
  "Anxiety",
  "Eczema",
  "Psoriasis",
  "Acne",
  "Cold",
  "Flu",
  "Pneumonia",
  "Ear Infection",
  "Urinary Tract Infection",
  "Kidney Infection",
  "Bladder Infection",
  "Gonorrhea",
  "Chlamydia",
  "Syphilis",
  "Heart Disease",
  "Diabetes",
  "Obesity",
  "Arthritis",
];

export default symp;
